<?php
add_action('init', function () {
    register_post_type('information_session', array(
        'labels' => array(
            'name' => '学校説明会',
            'singular_name' => '学校説明会',
            'menu_name' => '学校説明会',
            'all_items' => '学校説明会 一覧',
            'edit_item' => '学校説明会 を編集',
            'view_item' => '学校説明会 を表示',
            'view_items' => '学校説明会 を表示',
            'add_new_item' => '新規学校説明会を追加',
            'add_new' => '新規学校説明会を追加',
            'new_item' => '新規 学校説明会',
            'parent_item_colon' => '親の学校説明会:',
            'search_items' => '学校説明会 を検索',
            'not_found' => '学校説明会 が見つかりませんでした。',
            'not_found_in_trash' => 'ゴミ箱に学校説明会はありません',
            'archives' => '学校説明会 アーカイブ',
            'attributes' => '学校説明会 の属性',
            'insert_into_item' => '学校説明会 に挿入',
            'uploaded_to_this_item' => 'この 学校説明会 にアップロードされました',
            'filter_items_list' => '学校説明会 リストを絞り込み',
            'filter_by_date' => '学校説明会 日時で絞り込み',
            'items_list_navigation' => '学校説明会 list navigation',
            'items_list' => '学校説明会 リスト',
            'item_published' => '学校説明会 を公開しました。',
            'item_published_privately' => '学校説明会 published privately.',
            'item_reverted_to_draft' => '学校説明会 を下書きに戻しました。',
            'item_scheduled' => '学校説明会 を予約しました。',
            'item_updated' => '学校説明会 を更新しました。',
            'item_link' => '学校説明会 リンク',
            'item_link_description' => '学校説明会 へのリンク。',
        ),
        'public' => true,
        'show_in_rest' => true,
        'menu_icon' => 'dashicons-admin-post',
        'supports' => array(
            0 => 'title',
            1 => 'revisions',
            2 => 'custom-fields',
        ),
        'delete_with_user' => false,
    ));
});